<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7OLPSVN6" failures="2" tests="7" name="Test" time="72.661" errors="0" timestamp="2024-08-04T21:13:55 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="varify_account_registration" time="2.486"/>
  <testcase classname="testCases.TC002_LoginTest" name="verify_Login" time="1.782"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="4.608"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="10.989">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_LoginDDT(TC003_LoginDDT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="15.036"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="13.888"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="11.206">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_LoginDDT(TC003_LoginDDT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
